// This file is generated by version.py. do not modify this file manually.
#pragma once

#include "./src_light/log.h"

#define APPVER_MAJOR (0)
#define APPVER_MINOR (1)
#define APPVER_BUILD (4)
#if LOGLEVEL >= lOGLEVEL_ERROR
#define VERSION_DESCRIPTION "add ERROR"
#elif LOGLEVEL >= LOGLEVEL_WARNING
#define VERSION_DESCRIPTION "add WARNING"
#elif LOGLEVEL >= LOGLEVEL_INFO
#define VERSION_DESCRIPTION "add INFO"
#elif LOGLEVEL >= LOGLEVEL_DEBUG
#define VERSION_DESCRIPTION "add DEBUG"
#elif LOGLEVEL >= LOGLEVEL_VERBOSE
#define VERSION_DESCRIPTION "add VERBOSE"
#else
#define VERSION_DESCRIPTION "no log"
#endif
// #define _ANDONDEBUG (0)